import localFont from 'next/font/local'
import './globals.css'

const IRANSansX = localFont({
  src: [
    {
      path: './../public/fonts/woff2/IRANSansX-thin.woff2',
      weight: '100',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-UltraLight.woff2',
      weight: '200',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-light.woff2',
      weight: '300',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-regular.woff2',
      weight: '400',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-medium.woff2',
      weight: '500',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-bold.woff2',
      weight: '600',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-demibold.woff2',
      weight: '700',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-extrabold.woff2',
      weight: '800',
      display: 'swap',
      style: 'normal'
    },
    {
      path: './../public/fonts/woff2/IRANSansX-black.woff2',
      weight: '900',
      display: 'swap',
      style: 'normal'
    }
  ],
  variable: '--font-IranSans'
})

export const metadata = {
  title: 'Quiz App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={IRANSansX.className}>{children}</body>
    </html>
  )
}
